name: End-to-End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile
        cd client && pnpm install --frozen-lockfile
        cd ../server && pnpm install --frozen-lockfile
    
    - name: Install Playwright
      run: npx playwright install --with-deps
    
    - name: Start backend server
      run: |
        cd server
        npm run start:test &
        sleep 10
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: test-secret
        NODE_ENV: test
        PORT: 5000
    
    - name: Start frontend server
      run: |
        cd client
        npm run dev &
        sleep 10
      env:
        VITE_API_URL: http://localhost:5000
    
    - name: Run E2E tests
      run: npx playwright test
      env:
        BASE_URL: http://localhost:5173
        API_URL: http://localhost:5000
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-videos
        path: test-results/
        retention-days: 30 